- name: Install REDIS
  apt: pkg=redis-server state=present update_cache=yes
  tags: deps

- name: Install dependencies
  apt: pkg={{ item }} update_cache=yes state=present
  with_items:
   - python-pycurl
   - python-apt
   - python-setuptools
  tags: deps

- easy_install: name=pip
  tags: deps

- name: Install ES Curator
  pip: name=elasticsearch-curator
  tags: deps

- name: Configure Redis
  template: src=redis.conf dest=/etc/redis/redis.conf
  notify: Restart Redis

- name: Add Logstash repository
  apt_repository: repo="deb http://packages.elasticsearch.org/logstash/{{ aggregator.logstash_version }}/debian stable main" state=present

- name: Add Logstash repository key
  apt_key: url="http://packages.elasticsearch.org/GPG-KEY-elasticsearch" state=present

- name: Install Logstash
  apt: pkg={{ item }} update_cache=yes state=present
  with_items:
   - logstash
   - logstash-contrib

- name: Logstash set heap size
  action: >
     lineinfile dest=/etc/init.d/logstash state=present
     regexp="^LS_HEAP_SIZE="
     line='LS_HEAP_SIZE="{{aggregator.config.logstash_heap_size|int}}m"'
  notify: Restart Logstash

- name: Install Logstash packetbeat configuration
  template: src=logstash_packetbeat.conf dest=/etc/logstash/conf.d/logstash_packetbeat.conf
  notify: Restart Logstash

- name: Start Logstash
  service: name=elasticsearch state=started enabled=yes

- name: Schedule curator for Packetbeat
  cron: >
        name='Curate Packetbeat'
        hour=2 minute=15
        job="{{ curator_bin }} -D -p packetbeat- -d {{ aggregator.config.days_of_history }}"
        user=elasticsearch cron_file=packetbeat


- name: Schedule curator for Logstash
  cron: >
        name='Curate Logstash'
        hour=3 minute=15
        job="{{ curator_bin }} -D -p logstash- -d {{ aggregator.config.days_of_history }}"
        user=elasticsearch cron_file=packetbeat
