kibana:
    url: https://github.com/packetbeat/kibana/releases/download/v3.1.0-pb
    archive: kibana-3.1.0-packetbeat.tar.gz

    config:
        server_name: "localhost"
        nginx_disable_default: true
        elasticsearch_url: '"http://"+window.location.hostname+"/ES"'

# Find aggregator's IP address from the inventory vars
aggregator_bind_iface: "{{ hostvars[groups['aggregator'][0]].get('main_iface', 'eth0') }}"
aggregator_bind_ip: "{{ hostvars[groups['aggregator'][0]]['ansible_' + aggregator_bind_iface ].ipv4.address }}"
